eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


server:
  port: ${PORT:8091}
spring:
  application:
    name: eclass-service
  cloud:
    config:
      enabled: ${CONFIG_SERVER_ENABLED:true}
      uri: ${CONFIG_SERVER_URI:http://localhost:8888}
      failFast: ${CONFIG_SERVER_FAILFAST:false}
    service-registry:
      auto-registration:
        enabled: ${DISCOVERY_ENABLED:false}
        fail-fast: ${DISCOVERY_FAILFAST:true}
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    properties:
      hibernate:
        type: debug
        temp:
          use_jdbc_metadata_defaults: false
        id:
          new_generator_mappings: true